[package]
name = "igraph-sys"
version = "0.1.0"
edition = "2024"
description = "Raw FFI bindings to the igraph C library"
links = "igraph"

[features]
# Regenerate bindings and update src/bindings.rs for committing.
regenerate = []

[build-dependencies]
cmake = "0.1"
bindgen = "0.71"
